[project]
name = "speech-processing-lab-biu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
    "pydantic>=2.13.4",
]

[project.scripts]
speech-processing-lab-biu = "speech_processing_lab_biu:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "assertpy>=1.1",
    "pytest>=9.1.1",
    "ruff>=0.16.3",
]
